var line1,line2,line3,line4,line5,line6,line7,line8;
var inv1,inv2,inv3,iv4,iv5,inv6,inv7,inv8,inv9;
var a1,a2,a3,a4,a5,a6,a7,a8,a9;
var s1,s2,s3,s4,s5,s6,s7,s8,s9;
var gamemode=0;
var chance=0;
var chance1,chance2;
var C,O;
var q1,q2,q3,q4,q5,q6,q7,q8,q9;
var w1,w2,w3,w4,w5,w6,w7,w8,w9;
var e1,e2,e3,e4,e5,e6,e7,e8,e9;
let pass=0;
function preload(){
 C=loadImage("png/cross.png")
 O=loadImage("png/O.png")
}
function setup(){
  alert("File has been created by Shresth Sharma and "+"All the copyrights are reserved");
    let person = prompt("File is protected please enter PIN", "");
    if (person == "3288") {
        pass=1
    } else{
        alert("Wrong PIN");
    }
    if(pass===1){
 createCanvas(800,600);
 button();
 sprites();
    }
}
function draw(){
  if(pass===1){
 background(0,255,0);
 if(gamemode===0){
   chance1.visible=true;
   chance2.visible=false;
 }
 if(gamemode===1){
   chance2.visible=true;
   chance1.visible=false;
 }
 
 main();
 main1();
 win();
 drawSprites();
 textSize(20);
 fill("blue");
 text("4",406.66,266.99);
 text("1",406.66,133.66);
 text("7",406.66,400.33);
 text("5",539.99,266.99);
 text("2",539.99,133.66);
 text("8",539.99,400.33);
 text("6",673.33,266.99);
 text("3",673.33,133.66);
 text("9",673.33,400.33);
}
}
function main(){
    if(gamemode===0){
      chance1.visible=true;
      chance2.visible=false;
      if(keyDown("1")&&a2.visible===false&&s2.visible===false){
        a2.visible=true;
        gamemode=1;
        q2.shapeColor=("yellow")
      }
      if(keyDown("2")&&a5.visible===false&&s5.visible===false){
        a5.visible=true;
        gamemode=1;
        q5.shapeColor=("yellow")
      }
      if(keyDown("3")&&a8.visible===false&&s8.visible===false){
        a8.visible=true;
        gamemode=1;
        q8.shapeColor=("yellow")
      }
      if(keyDown("4")&&a1.visible===false&&s1.visible===false){
        a1.visible=true;
        gamemode=1;
        q1.shapeColor=("yellow")
      }
      if(keyDown("5")&&a4.visible===false&&s4.visible===false){
        a4.visible=true;
        gamemode=1;
        q4.shapeColor=("yellow")
      }
      if(keyDown("6")&&a7.visible===false&&s7.visible===false){
        a7.visible=true;
        gamemode=1;
        q7.shapeColor=("yellow")
      }
      if(keyDown("7")&&a3.visible===false&&s3.visible===false){
        a3.visible=true;
        gamemode=1;
        q3.shapeColor=("yellow")
      }
      if(keyDown("8")&&a6.visible===false&&s6.visible===false){
        a6.visible=true;
        gamemode=1;
        q6.shapeColor=("yellow")
      }
      if(keyDown("9")&&a9.visible===false&&s9.visible===false){
        a9.visible=true;
        gamemode=1;
        q9.shapeColor=("yellow")
      }
  
     }
     if(gamemode===1){
      chance2.visible=true;
      chance1.visible=false;
      if(keyDown("1")&&a2.visible===false&&s2.visible===false){
        s2.visible=true;
        gamemode=2;
        q2.shapeColor=("pink")
      }
      if(keyDown("2")&&a5.visible===false&&s5.visible===false){
        s5.visible=true;
        gamemode=2;
        q5.shapeColor=("pink")
      }
      if(keyDown("3")&&a8.visible===false&&s8.visible===false){
        s8.visible=true;
        gamemode=2;
        q8.shapeColor=("pink")
      }
      if(keyDown("4")&&a1.visible===false&&s1.visible===false){
        s1.visible=true;
        gamemode=2;
        q1.shapeColor=("pink")
      }
      if(keyDown("5")&&a4.visible===false&&s4.visible===false){
        s4.visible=true;
        gamemode=2;
        q4.shapeColor=("pink")
      }
      if(keyDown("6")&&a7.visible===false&&s7.visible===false){
        s7.visible=true;
        gamemode=2;
        q7.shapeColor=("pink")
      }
      if(keyDown("7")&&a3.visible===false&&s3.visible===false){
        s3.visible=true;
        gamemode=2;
        q3.shapeColor=("pink")
      }
      if(keyDown("8")&&a6.visible===false&&s6.visible===false){
        s6.visible=true;
        gamemode=2;
        q6.shapeColor=("pink")
      }
      if(keyDown("9")&&a9.visible===false&&s9.visible===false){
        s9.visible=true;
        gamemode=2;
        q9.shapeColor=("pink")
      }
  
     }
     if(gamemode===2){
      chance1.visible=true;
      chance2.visible=false;
      if(keyDown("1")&&a2.visible===false&&s2.visible===false){
        a2.visible=true;
        gamemode=3;
        q2.shapeColor=("yellow")
      }
      if(keyDown("2")&&a5.visible===false&&s5.visible===false){
        a5.visible=true;
        gamemode=3;
        q5.shapeColor=("yellow")
      }
      if(keyDown("3")&&a8.visible===false&&s8.visible===false){
        a8.visible=true;
        gamemode=3;
        q8.shapeColor=("yellow")
      }
      if(keyDown("4")&&a1.visible===false&&s1.visible===false){
        a1.visible=true;
        gamemode=3;
        q1.shapeColor=("yellow")
      }
      if(keyDown("5")&&a4.visible===false&&s4.visible===false){
        a4.visible=true;
        gamemode=3;
        q4.shapeColor=("yellow")
      }
      if(keyDown("6")&&a7.visible===false&&s7.visible===false){
        a7.visible=true;
        gamemode=3;
        q7.shapeColor=("yellow")
      }
      if(keyDown("7")&&a3.visible===false&&s3.visible===false){
        a3.visible=true;
        gamemode=3;
        q3.shapeColor=("yellow")
      }
      if(keyDown("8")&&a6.visible===false&&s6.visible===false){
        a6.visible=true;
        gamemode=3;
        q6.shapeColor=("yellow")
      }
      if(keyDown("9")&&a9.visible===false&&s9.visible===false){
        a9.visible=true;
        gamemode=3;
        q9.shapeColor=("yellow")
      }
  
     }
     if(gamemode===3){
      chance1.visible=false;
      chance2.visible=true;
      if(keyDown("1")&&a2.visible===false&&s2.visible===false){
        s2.visible=true;
        gamemode=4;
        q2.shapeColor=("pink")
      }
      if(keyDown("2")&&a5.visible===false&&s5.visible===false){
        s5.visible=true;
        gamemode=4;
        q5.shapeColor=("pink")
      }
      if(keyDown("3")&&a8.visible===false&&s8.visible===false){
        s8.visible=true;
        gamemode=4;
        q8.shapeColor=("pink")
      }
      if(keyDown("4")&&a1.visible===false&&s1.visible===false){
        s1.visible=true;
        gamemode=4;
        q1.shapeColor=("pink")
      }
      if(keyDown("5")&&a4.visible===false&&s4.visible===false){
        s4.visible=true;
        gamemode=4;
        q4.shapeColor=("pink")
      }
      if(keyDown("6")&&a7.visible===false&&s7.visible===false){
        s7.visible=true;
        gamemode=4;
        q7.shapeColor=("pink")
      }
      if(keyDown("7")&&a3.visible===false&&s3.visible===false){
        s3.visible=true;
        gamemode=4;
        q3.shapeColor=("pink")
      }
      if(keyDown("8")&&a6.visible===false&&s6.visible===false){
        s6.visible=true;
        gamemode=4;
        q6.shapeColor=("pink")
      }
      if(keyDown("9")&&a9.visible===false&&s9.visible===false){
        s9.visible=true;
        gamemode=4;
        q9.shapeColor=("pink")
      }
  
     }
     if(gamemode===4){
      chance1.visible=true;
      chance2.visible=false;
      if(keyDown("1")&&a2.visible===false&&s2.visible===false){
        a2.visible=true;
        gamemode=5;
        q2.shapeColor=("yellow")
      }
      if(keyDown("2")&&a5.visible===false&&s5.visible===false){
        a5.visible=true;
        gamemode=5;
        q5.shapeColor=("yellow")
      }
      if(keyDown("3")&&a8.visible===false&&s8.visible===false){
        a8.visible=true;
        gamemode=5;
        q8.shapeColor=("yellow")
      }
      if(keyDown("4")&&a1.visible===false&&s1.visible===false){
        a1.visible=true;
        gamemode=5;
        q1.shapeColor=("yellow")
      }
      if(keyDown("5")&&a4.visible===false&&s4.visible===false){
        a4.visible=true;
        gamemode=5;
        q4.shapeColor=("yellow")
      }
      if(keyDown("6")&&a7.visible===false&&s7.visible===false){
        a7.visible=true;
        gamemode=5;
        q7.shapeColor=("yellow")
      }
      if(keyDown("7")&&a3.visible===false&&s3.visible===false){
        a3.visible=true;
        gamemode=5;
        q3.shapeColor=("yellow")
      }
      if(keyDown("8")&&a6.visible===false&&s6.visible===false){
        a6.visible=true;
        gamemode=5;
        q6.shapeColor=("yellow")
      }
      if(keyDown("9")&&a9.visible===false&&s9.visible===false){
        a9.visible=true;
        gamemode=5;
        q9.shapeColor=("yellow")
      }
  
     }
     if(gamemode===5){
      chance1.visible=false;
      chance2.visible=true;
      if(keyDown("1")&&a2.visible===false&&s2.visible===false){
        s2.visible=true;
        gamemode=6;
        q2.shapeColor=("pink")
      }
      if(keyDown("2")&&a5.visible===false&&s5.visible===false){
        s5.visible=true;
        gamemode=6;
        q5.shapeColor=("pink")
      }
      if(keyDown("3")&&a8.visible===false&&s8.visible===false){
        s8.visible=true;
        gamemode=6;
        q8.shapeColor=("pink")
      }
      if(keyDown("4")&&a1.visible===false&&s1.visible===false){
        s1.visible=true;
        gamemode=6;
        q1.shapeColor=("pink")
      }
      if(keyDown("5")&&a4.visible===false&&s4.visible===false){
        s4.visible=true;
        gamemode=6;
        q4.shapeColor=("pink")
      }
      if(keyDown("6")&&a7.visible===false&&s7.visible===false){
        s7.visible=true;
        gamemode=6;
        q7.shapeColor=("pink")
      }
      if(keyDown("7")&&a3.visible===false&&s3.visible===false){
        s3.visible=true;
        gamemode=6;
        q3.shapeColor=("pink")
      }
      if(keyDown("8")&&a6.visible===false&&s6.visible===false){
        s6.visible=true;
        gamemode=6;
        q6.shapeColor=("pink")
      }
      if(keyDown("9")&&a9.visible===false&&s9.visible===false){
        s9.visible=true;
        gamemode=6;
        q9.shapeColor=("pink")
      }
  
     }
     if(gamemode===6){
      chance1.visible=true;
      chance2.visible=false;
      if(keyDown("1")&&a2.visible===false&&s2.visible===false){
        a2.visible=true;
        gamemode=7;
        q2.shapeColor=("yellow")
      }
      if(keyDown("2")&&a5.visible===false&&s5.visible===false){
        a5.visible=true;
        gamemode=7;
        q5.shapeColor=("yellow")
      }
      if(keyDown("3")&&a8.visible===false&&s8.visible===false){
        a8.visible=true;
        gamemode=7;
        q8.shapeColor=("yellow")
      }
      if(keyDown("4")&&a1.visible===false&&s1.visible===false){
        a1.visible=true;
        gamemode=7;
        q1.shapeColor=("yellow")
      }
      if(keyDown("5")&&a4.visible===false&&s4.visible===false){
        a4.visible=true;
        gamemode=7;
        q4.shapeColor=("yellow")
      }
      if(keyDown("6")&&a7.visible===false&&s7.visible===false){
        a7.visible=true;
        gamemode=7;
        q7.shapeColor=("yellow")
      }
      if(keyDown("7")&&a3.visible===false&&s3.visible===false){
        a3.visible=true;
        gamemode=7;
        q3.shapeColor=("yellow")
      }
      if(keyDown("8")&&a6.visible===false&&s6.visible===false){
        a6.visible=true;
        gamemode=7;
        q6.shapeColor=("yellow")
      }
      if(keyDown("9")&&a9.visible===false&&s9.visible===false){
        a9.visible=true;
        gamemode=7;
        q9.shapeColor=("yellow")
      }
  
     }
     if(gamemode===7){
      chance1.visible=false;
      chance2.visible=true;
      if(keyDown("1")&&a2.visible===false&&s2.visible===false){
        s2.visible=true;
        gamemode=8;
        q2.shapeColor=("pink")
      }
      if(keyDown("2")&&a5.visible===false&&s5.visible===false){
        s5.visible=true;
        gamemode=8;
        q5.shapeColor=("pink")
      }
      if(keyDown("3")&&a8.visible===false&&s8.visible===false){
        s8.visible=true;
        gamemode=8;
        q8.shapeColor=("pink")
      }
      if(keyDown("4")&&a1.visible===false&&s1.visible===false){
        s1.visible=true;
        gamemode=8;
        q1.shapeColor=("pink")
      }
      if(keyDown("5")&&a4.visible===false&&s4.visible===false){
        s4.visible=true;
        gamemode=8;
        q4.shapeColor=("pink")
      }
      if(keyDown("6")&&a7.visible===false&&s7.visible===false){
        s7.visible=true;
        gamemode=8;
        q7.shapeColor=("pink")
      }
      if(keyDown("7")&&a3.visible===false&&s3.visible===false){
        s3.visible=true;
        gamemode=8;
        q3.shapeColor=("pink")
      }
      if(keyDown("8")&&a6.visible===false&&s6.visible===false){
        s6.visible=true;
        gamemode=8;
        q6.shapeColor=("pink")
      }
      if(keyDown("9")&&a9.visible===false&&s9.visible===false){
        s9.visible=true;
        gamemode=8;
        q9.shapeColor=("pink")
      }
  
     }
     if(gamemode===8){
      chance1.visible=true;
      chance2.visible=false;
      if(keyDown("1")&&a2.visible===false&&s2.visible===false){
        a2.visible=true;
        gamemode=9;
        q2.shapeColor=("yellow")
      }
      if(keyDown("2")&&a5.visible===false&&s5.visible===false){
        a5.visible=true;
        gamemode=9;
        q5.shapeColor=("yellow")
      }
      if(keyDown("3")&&a8.visible===false&&s8.visible===false){
        a8.visible=true;
        gamemode=9;
        q8.shapeColor=("yellow")
      }
      if(keyDown("4")&&a1.visible===false&&s1.visible===false){
        a1.visible=true;
        gamemode=9;
        q1.shapeColor=("yellow")
      }
      if(keyDown("5")&&a4.visible===false&&s4.visible===false){
        a4.visible=true;
        gamemode=9;
        q4.shapeColor=("yellow")
      }
      if(keyDown("6")&&a7.visible===false&&s7.visible===false){
        a7.visible=true;
        gamemode=9;
        q7.shapeColor=("yellow")
      }
      if(keyDown("7")&&a3.visible===false&&s3.visible===false){
        a3.visible=true;
        gamemode=9;
        q3.shapeColor=("yellow")
      }
      if(keyDown("8")&&a6.visible===false&&s6.visible===false){
        a6.visible=true;
        gamemode=9;
        q6.shapeColor=("yellow")
      }
      if(keyDown("9")&&a9.visible===false&&s9.visible===false){
        a9.visible=true;
        gamemode=9;
        q9.shapeColor=("yellow")
      }
  
     }
  }
  function win(){
    if(a2.visible===true&&a5.visible===true&&a8.visible===true){
        chance1.visible=false;
        chance2.visible=false;
        textSize(130);
        fill("red");
        text("X",50,250);
        text("WIN",30,350);
        q2.shapeColor=("orange");
        q5.shapeColor=("orange");
        q8.shapeColor=("orange");
       }
       else if(a1.visible===true&&a4.visible===true&&a7.visible===true){
        chance1.visible=false;
        chance2.visible=false;
        textSize(130);
        fill("red");
        text("X",50,250);
        text("WIN",30,350);
        q1.shapeColor=("orange");
        q4.shapeColor=("orange");
        q7.shapeColor=("orange");
       }
       else if(a3.visible===true&&a6.visible===true&&a9.visible===true){
        chance1.visible=false;
        chance2.visible=false;
        textSize(130);
        fill("red");
        text("X",50,250);
        text("WIN",30,350);
        q3.shapeColor=("orange");
        q6.shapeColor=("orange");
        q9.shapeColor=("orange");
       }
       else if(a2.visible===true&&a1.visible===true&&a3.visible===true){
        chance1.visible=false;
        chance2.visible=false;
        textSize(130);
        fill("red");
        text("X",50,250);
        text("WIN",30,350);
        q2.shapeColor=("orange");
        q1.shapeColor=("orange");
        q3.shapeColor=("orange");
       }
       else if(a5.visible===true&&a4.visible===true&&a6.visible===true){
        chance1.visible=false;
        chance2.visible=false;
        textSize(130);
        fill("red");
        text("X",50,250);
        text("WIN",30,350);
        q5.shapeColor=("orange");
        q4.shapeColor=("orange");
        q6.shapeColor=("orange");
       }
       else if(a8.visible===true&&a7.visible===true&&a9.visible===true){
        chance1.visible=false;
        chance2.visible=false;
        textSize(130);
        fill("red");
        text("X",50,250);
        text("WIN",30,350);
        q8.shapeColor=("orange");
        q7.shapeColor=("orange");
        q9.shapeColor=("orange");
       }
       else if(a2.visible===true&&a4.visible===true&&a9.visible===true){
        chance1.visible=false;
        chance2.visible=false;
        textSize(130);
        fill("red");
        text("X",50,250);
        text("WIN",30,350);
        q2.shapeColor=("orange");
        q4.shapeColor=("orange");
        q9.shapeColor=("orange");
       }
       else if(a8.visible===true&&a4.visible===true&&a3.visible===true){
        chance1.visible=false;
        chance2.visible=false;
        textSize(130);
        fill("red");
        text("X",50,250);
        text("WIN",30,350);
        q8.shapeColor=("orange");
        q4.shapeColor=("orange");
        q3.shapeColor=("orange");
       }
       else if(s2.visible===true&&s5.visible===true&&s8.visible===true){
        chance1.visible=false;
        chance2.visible=false;
        textSize(130);
        fill("red");
        text("O",50,250);
        text("WIN",30,350);
        q2.shapeColor=("orange");
        q5.shapeColor=("orange");
        q8.shapeColor=("orange");
       }
       else if(s1.visible===true&&s4.visible===true&&s7.visible===true){
        chance1.visible=false;
        chance2.visible=false;
        textSize(130);
        fill("red");
        text("O",50,250);
        text("WIN",30,350);
        q1.shapeColor=("orange");
        q4.shapeColor=("orange");
        q7.shapeColor=("orange");
       }
       else if(s3.visible===true&&s6.visible===true&&s9.visible===true){
        chance1.visible=false;
        chance2.visible=false;
        textSize(130);
        fill("red");
        text("O",50,250);
        text("WIN",30,350);
        q3.shapeColor=("orange");
        q6.shapeColor=("orange");
        q9.shapeColor=("orange");
       }
       else if(s2.visible===true&&s1.visible===true&&s3.visible===true){
        chance1.visible=false;
        chance2.visible=false;
        textSize(130);
        fill("red");
        text("O",50,250);
        text("WIN",30,350);
        q2.shapeColor=("orange");
        q1.shapeColor=("orange");
        q3.shapeColor=("orange");
       }
       else if(s5.visible===true&&s4.visible===true&&s6.visible===true){
        chance1.visible=false;
        chance2.visible=false;
        textSize(130);
        fill("red");
        text("O",50,250);
        text("WIN",30,350);
        q5.shapeColor=("orange");
        q4.shapeColor=("orange");
        q6.shapeColor=("orange");
       }
       else if(s8.visible===true&&s7.visible===true&&s9.visible===true){
        chance1.visible=false;
        chance2.visible=false;
        textSize(130);
        fill("red");
        text("O",50,250);
        text("WIN",30,350);
        q8.shapeColor=("orange");
        q7.shapeColor=("orange");
        q9.shapeColor=("orange");
       }
       else if(s2.visible===true&&s4.visible===true&&s9.visible===true){
        chance1.visible=false;
        chance2.visible=false;
        textSize(130);
        fill("red");
        text("O",50,250);
        text("WIN",30,350);
        q2.shapeColor=("orange");
        q4.shapeColor=("orange");
        q9.shapeColor=("orange");
       }
       else if(s8.visible===true&&s4.visible===true&&s3.visible===true){
        chance1.visible=false;
        chance2.visible=false;
        textSize(130);
        fill("red");
        text("O",50,250);
        text("WIN",30,350);
        q8.shapeColor=("orange");
        q4.shapeColor=("orange");
        q3.shapeColor=("orange");
       }
       else {
         if(gamemode===9){
          chance1.visible=false;
          chance2.visible=false;
          textSize(150);
          fill("red");
          text("Tie",50,300);
         }
       }
}
function sprites(){
  line1=createSprite(300,300,10,410);
  line2=createSprite(700,300,10,410);
  line3=createSprite(500,100,410,10);
  line4=createSprite(500,500,410,10);
  line5=createSprite(433.33,300,10,410);
  line6=createSprite(566.66,300,10,410);
  line7=createSprite(500,233.33,410,10);
  line8=createSprite(500,366.67,410,10);
  line1.shapeColor=("blue");
  line2.shapeColor=("blue");
  line3.shapeColor=("blue");
  line4.shapeColor=("blue");
  line5.shapeColor=("blue");
  line6.shapeColor=("blue");
  line7.shapeColor=("blue");
  line8.shapeColor=("blue");
  q1=createSprite(366.66,299.99,120.33,120.33);
  q2=createSprite(366.66,166.66,120.33,120.33);
  q3=createSprite(366.66,433.33,120.33,120.33);
  q4=createSprite(499.99,299.99,120.33,120.33);
  q5=createSprite(499.99,166.66,120.33,120.33);
  q6=createSprite(499.99,433.33,120.33,120.33);
  q7=createSprite(633.33,299.99,120.33,120.33);
  q8=createSprite(633.33,166.66,120.33,120.33);
  q9=createSprite(633.33,433.33,120.33,120.33);
  q1.shapeColor=("Green");
  q2.shapeColor=("Green");
  q3.shapeColor=("Green");
  q4.shapeColor=("Green");
  q5.shapeColor=("Green");
  q6.shapeColor=("Green");
  q7.shapeColor=("Green");
  q8.shapeColor=("Green");
  q9.shapeColor=("Green");
  inv1=createSprite(366.66,299.99,120.33,120.33);
  inv2=createSprite(366.66,166.66,120.33,120.33);
  inv3=createSprite(366.66,433.33,120.33,120.33);
  inv4=createSprite(499.99,299.99,120.33,120.33);
  inv5=createSprite(499.99,166.66,120.33,120.33);
  inv6=createSprite(499.99,433.33,120.33,120.33);
  inv7=createSprite(633.33,299.99,120.33,120.33);
  inv8=createSprite(633.33,166.66,120.33,120.33);
  inv9=createSprite(633.33,433.33,120.33,120.33);
  a1=createSprite(366.66,299.99,120.33,120.33);
  a2=createSprite(366.66,166.66,120.33,120.33);
  a3=createSprite(366.66,433.33,120.33,120.33);
  a4=createSprite(499.99,299.99,120.33,120.33);
  a5=createSprite(499.99,166.66,120.33,120.33);
  a6=createSprite(499.99,433.33,120.33,120.33);
  a7=createSprite(633.33,299.99,120.33,120.33);
  a8=createSprite(633.33,166.66,120.33,120.33);
  a9=createSprite(633.33,433.33,120.33,120.33);
  s1=createSprite(366.66,299.99,120.33,120.33);
  s2=createSprite(366.66,166.66,120.33,120.33);
  s3=createSprite(366.66,433.33,120.33,120.33);
  s4=createSprite(499.99,299.99,120.33,120.33);
  s5=createSprite(499.99,166.66,120.33,120.33);
  s6=createSprite(499.99,433.33,120.33,120.33);
  s7=createSprite(633.33,299.99,120.33,120.33);
  s8=createSprite(633.33,166.66,120.33,120.33);
  s9=createSprite(633.33,433.33,120.33,120.33);
  a1.scale=2.5;
  a2.scale=2.5;
  a3.scale=2.5;
  a4.scale=2.5;
  a5.scale=2.5;
  a6.scale=2.5;
  a7.scale=2.5;
  a8.scale=2.5;
  a9.scale=2.5;
  s1.scale=2.5;
  s2.scale=2.5;
  s3.scale=2.5;
  s4.scale=2.5;
  s5.scale=2.5;
  s6.scale=2.5;
  s7.scale=2.5;
  s8.scale=2.5;
  s9.scale=2.5;
  inv1.visible=false;
  inv2.visible=false;
  inv3.visible=false;
  inv4.visible=false;
  inv5.visible=false;
  inv6.visible=false;
  inv7.visible=false;
  inv8.visible=false;
  inv9.visible=false;
  a1.visible=false;
  a2.visible=false;
  a3.visible=false;
  a4.visible=false;
  a5.visible=false;
  a6.visible=false;
  a7.visible=false;
  a8.visible=false;
  a9.visible=false;
  s1.visible=false;
  s2.visible=false;
  s3.visible=false;
  s4.visible=false;
  s5.visible=false;
  s6.visible=false;
  s7.visible=false;
  s8.visible=false;
  s9.visible=false;
  a1.addImage("c",C);
  a2.addImage("c",C);
  a3.addImage("c",C);
  a4.addImage("c",C);
  a5.addImage("c",C);
  a6.addImage("c",C);
  a7.addImage("c",C);
  a8.addImage("c",C);
  a9.addImage("c",C);
  s1.addImage("c",O);
  s2.addImage("c",O);
  s3.addImage("c",O);
  s4.addImage("c",O);
  s5.addImage("c",O);
  s6.addImage("c",O);
  s7.addImage("c",O);
  s8.addImage("c",O);
  s9.addImage("c",O);
  chance1=createSprite(150,300,200,200);
  chance2=createSprite(150,300,200,200);
  chance1.visible=false;
  chance2.visible=false;
  chance1.addImage("o",C);
  chance2.addImage("c",O);
  chance1.scale=5;
  chance2.scale=5;
 }
 function button(){
  e1=createButton('4');
  e2=createButton('1');
  e3=createButton('7');
  e4=createButton('5');
  e5=createButton('2');
  e6=createButton('8');
  e7=createButton('6');
  e8=createButton('3');
  e9=createButton('9');
  e2.position(050,520);
  e5.position(120,520);
  e8.position(200,520);
  e1.position(280,520);
  e4.position(360,520);
  e7.position(440,520);
  e3.position(520,520);
  e6.position(600,520);
  e9.position(680,520);
  e1.size(80.33,80.33);
  e2.size(80.33,80.33);
  e3.size(80.33,80.33);
  e4.size(80.33,80.33);
  e5.size(80.33,80.33);
  e6.size(80.33,80.33);
  e7.size(80.33,80.33);
  e8.size(80.33,80.33);
  e9.size(80.33,80.33);

}
function main1(){
  if(gamemode===0){
      e1.mousePressed(()=>{
      
          if(a1.visible===false&&s1.visible===false){
              a1.visible=true;
              gamemode=1;
              q1.shapeColor=("yellow")
          }
      });
      e2.mousePressed(()=>{
          
          if(a2.visible===false&&s2.visible===false){
              a2.visible=true;
              gamemode=1;
              q2.shapeColor=("yellow")
          }
      });
      e3.mousePressed(()=>{
          
          if(a3.visible===false&&s3.visible===false){
              a3.visible=true;
              gamemode=1;
              q3.shapeColor=("yellow")
          }
      });
      e4.mousePressed(()=>{
          
          if(a4.visible===false&&s4.visible===false){
              a4.visible=true;
              gamemode=1;
              q4.shapeColor=("yellow")
          }
      });
      e5.mousePressed(()=>{
          
          if(a5.visible===false&&s5.visible===false){
              a5.visible=true;
              gamemode=1;
              q5.shapeColor=("yellow")
          }
      });
      e6.mousePressed(()=>{
          
          if(a6.visible===false&&s6.visible===false){
              a6.visible=true;
              gamemode=1;
              q6.shapeColor=("yellow")
          }
      });
      e7.mousePressed(()=>{
          
          if(a7.visible===false&&s7.visible===false){
              a7.visible=true;
              gamemode=1;
              q7.shapeColor=("yellow")
          }
      });
      e8.mousePressed(()=>{
          
          if(a8.visible===false&&s8.visible===false){
              a8.visible=true;
              gamemode=1;
              q8.shapeColor=("yellow")
          }
      });
      e9.mousePressed(()=>{
          
          if(a9.visible===false&&s9.visible===false){
              a9.visible=true;
              gamemode=1;
              q9.shapeColor=("yellow")
          }
      });
  }
  
  if(gamemode===1){
      e1.mousePressed(()=>{
      
          if(a1.visible===false&&s1.visible===false){
              s1.visible=true;
              gamemode=2;
              q1.shapeColor=("pink")
          }
      });
      e2.mousePressed(()=>{
          
          if(a2.visible===false&&s2.visible===false){
              s2.visible=true;
              gamemode=2;
              q2.shapeColor=("pink")
          }
      });
      e3.mousePressed(()=>{
          
          if(a3.visible===false&&s3.visible===false){
              s3.visible=true;
              gamemode=2;
              q3.shapeColor=("pink")
          }
      });
      e4.mousePressed(()=>{
          
          if(a4.visible===false&&s4.visible===false){
              s4.visible=true;
              gamemode=2;
              q4.shapeColor=("pink")
          }
      });
      e5.mousePressed(()=>{
          
          if(a5.visible===false&&s5.visible===false){
              s5.visible=true;
              gamemode=2;
              q5.shapeColor=("pink")
          }
      });
      e6.mousePressed(()=>{
          
          if(a6.visible===false&&s6.visible===false){
              s6.visible=true;
              gamemode=2;
              q6.shapeColor=("pink")
          }
      });
      e7.mousePressed(()=>{
          
          if(a7.visible===false&&s7.visible===false){
              s7.visible=true;
              gamemode=2;
              q7.shapeColor=("pink")
          }
      });
      e8.mousePressed(()=>{
          
          if(a8.visible===false&&s8.visible===false){
              s8.visible=true;
              gamemode=2;
              q8.shapeColor=("pink")
          }
      });
      e9.mousePressed(()=>{
          
          if(a9.visible===false&&s9.visible===false){
              s9.visible=true;
              gamemode=2;
              q9.shapeColor=("pink")
          }
      });
  }
  
  if(gamemode===2){
      e1.mousePressed(()=>{
      
          if(a1.visible===false&&s1.visible===false){
              a1.visible=true;
              gamemode=3;
              q1.shapeColor=("yellow")
          }
      });
      e2.mousePressed(()=>{
          
          if(a2.visible===false&&s2.visible===false){
              a2.visible=true;
              gamemode=3;
              q2.shapeColor=("yellow")
          }
      });
      e3.mousePressed(()=>{
          
          if(a3.visible===false&&s3.visible===false){
              a3.visible=true;
              gamemode=3;
              q3.shapeColor=("yellow")
          }
      });
      e4.mousePressed(()=>{
          
          if(a4.visible===false&&s4.visible===false){
              a4.visible=true;
              gamemode=3;
              q4.shapeColor=("yellow")
          }
      });
      e5.mousePressed(()=>{
          
          if(a5.visible===false&&s5.visible===false){
              a5.visible=true;
              gamemode=3;
              q5.shapeColor=("yellow")
          }
      });
      e6.mousePressed(()=>{
          
          if(a6.visible===false&&s6.visible===false){
              a6.visible=true;
              gamemode=3;
              q6.shapeColor=("yellow")
          }
      });
      e7.mousePressed(()=>{
          
          if(a7.visible===false&&s7.visible===false){
              a7.visible=true;
              gamemode=3;
              q7.shapeColor=("yellow")
          }
      });
      e8.mousePressed(()=>{
          
          if(a8.visible===false&&s8.visible===false){
              a8.visible=true;
              gamemode=3;
              q8.shapeColor=("yellow")
          }
      });
      e9.mousePressed(()=>{
          
          if(a9.visible===false&&s9.visible===false){
              a9.visible=true;
              gamemode=3;
              q9.shapeColor=("yellow")
          }
      });
  }
  
  if(gamemode===3){
      e1.mousePressed(()=>{
      
          if(a1.visible===false&&s1.visible===false){
              s1.visible=true;
              gamemode=4;
              q1.shapeColor=("")
          }
      });
      e2.mousePressed(()=>{
          
          if(a2.visible===false&&s2.visible===false){
              s2.visible=true;
              gamemode=4;
              q2.shapeColor=("")
          }
      });
      e3.mousePressed(()=>{
          
          if(a3.visible===false&&s3.visible===false){
              s3.visible=true;
              gamemode=4;
              q3.shapeColor=("")
          }
      });
      e4.mousePressed(()=>{
          
          if(a4.visible===false&&s4.visible===false){
              s4.visible=true;
              gamemode=4;
              q4.shapeColor=("")
          }
      });
      e5.mousePressed(()=>{
          
          if(a5.visible===false&&s5.visible===false){
              s5.visible=true;
              gamemode=4;
              q5.shapeColor=("")
          }
      });
      e6.mousePressed(()=>{
          
          if(a6.visible===false&&s6.visible===false){
              s6.visible=true;
              gamemode=4;
              q6.shapeColor=("")
          }
      });
      e7.mousePressed(()=>{
          
          if(a7.visible===false&&s7.visible===false){
              s7.visible=true;
              gamemode=4;
              q7.shapeColor=("")
          }
      });
      e8.mousePressed(()=>{
          
          if(a8.visible===false&&s8.visible===false){
              s8.visible=true;
              gamemode=4;
              q8.shapeColor=("")
          }
      });
      e9.mousePressed(()=>{
          
          if(a9.visible===false&&s9.visible===false){
              s9.visible=true;
              gamemode=4;
              q9.shapeColor=("")
          }
      });
  }
  
  if(gamemode===4){
      e1.mousePressed(()=>{
      
          if(a1.visible===false&&s1.visible===false){
              a1.visible=true;
              gamemode=5;
              q1.shapeColor=("yellow")
          }
      });
      e2.mousePressed(()=>{
          
          if(a2.visible===false&&s2.visible===false){
              a2.visible=true;
              gamemode=5;
              q2.shapeColor=("yellow")
          }
      });
      e3.mousePressed(()=>{
          
          if(a3.visible===false&&s3.visible===false){
              a3.visible=true;
              gamemode=5;
              q3.shapeColor=("yellow")
          }
      });
      e4.mousePressed(()=>{
          
          if(a4.visible===false&&s4.visible===false){
              a4.visible=true;
              gamemode=5;
              q4.shapeColor=("yellow")
          }
      });
      e5.mousePressed(()=>{
          
          if(a5.visible===false&&s5.visible===false){
              a5.visible=true;
              gamemode=5;
              q5.shapeColor=("yellow")
          }
      });
      e6.mousePressed(()=>{
          
          if(a6.visible===false&&s6.visible===false){
              a6.visible=true;
              gamemode=5;
              q6.shapeColor=("yellow")
          }
      });
      e7.mousePressed(()=>{
          
          if(a7.visible===false&&s7.visible===false){
              a7.visible=true;
              gamemode=5;
              q7.shapeColor=("yellow")
          }
      });
      e8.mousePressed(()=>{
          
          if(a8.visible===false&&s8.visible===false){
              a8.visible=true;
              gamemode=5;
              q8.shapeColor=("yellow")
          }
      });
      e9.mousePressed(()=>{
          
          if(a9.visible===false&&s9.visible===false){
              a9.visible=true;
              gamemode=5;
              q9.shapeColor=("yellow")
          }
      });
  }
  
  if(gamemode===5){
      e1.mousePressed(()=>{
      
          if(a1.visible===false&&s1.visible===false){
              s1.visible=true;
              gamemode=6;
              q1.shapeColor=("pink")
          }
      });
      e2.mousePressed(()=>{
          
          if(a2.visible===false&&s2.visible===false){
              s2.visible=true;
              gamemode=6;
              q2.shapeColor=("pink")
          }
      });
      e3.mousePressed(()=>{
          
          if(a3.visible===false&&s3.visible===false){
              s3.visible=true;
              gamemode=6;
              q3.shapeColor=("pink")
          }
      });
      e4.mousePressed(()=>{
          
          if(a4.visible===false&&s4.visible===false){
              s4.visible=true;
              gamemode=6;
              q4.shapeColor=("pink")
          }
      });
      e5.mousePressed(()=>{
          
          if(a5.visible===false&&s5.visible===false){
              s5.visible=true;
              gamemode=6;
              q5.shapeColor=("pink")
          }
      });
      e6.mousePressed(()=>{
          
          if(a6.visible===false&&s6.visible===false){
              s6.visible=true;
              gamemode=6;
              q6.shapeColor=("pink")
          }
      });
      e7.mousePressed(()=>{
          
          if(a7.visible===false&&s7.visible===false){
              s7.visible=true;
              gamemode=6;
              q7.shapeColor=("pink")
          }
      });
      e8.mousePressed(()=>{
          
          if(a8.visible===false&&s8.visible===false){
              s8.visible=true;
              gamemode=6;
              q8.shapeColor=("pink")
          }
      });
      e9.mousePressed(()=>{
          
          if(a9.visible===false&&s9.visible===false){
              s9.visible=true;
              gamemode=6;
              q9.shapeColor=("pink")
          }
      });
  }
  
  if(gamemode===6){
      e1.mousePressed(()=>{
      
          if(a1.visible===false&&s1.visible===false){
              a1.visible=true;
              gamemode=7;
              q1.shapeColor=("yellow")
          }
      });
      e2.mousePressed(()=>{
          
          if(a2.visible===false&&s2.visible===false){
              a2.visible=true;
              gamemode=7;
              q2.shapeColor=("yellow")
          }
      });
      e3.mousePressed(()=>{
          
          if(a3.visible===false&&s3.visible===false){
              a3.visible=true;
              gamemode=7;
              q3.shapeColor=("yellow")
          }
      });
      e4.mousePressed(()=>{
          
          if(a4.visible===false&&s4.visible===false){
              a4.visible=true;
              gamemode=7;
              q4.shapeColor=("yellow")
          }
      });
      e5.mousePressed(()=>{
          
          if(a5.visible===false&&s5.visible===false){
              a5.visible=true;
              gamemode=7;
              q5.shapeColor=("yellow")
          }
      });
      e6.mousePressed(()=>{
          
          if(a6.visible===false&&s6.visible===false){
              a6.visible=true;
              gamemode=7;
              q6.shapeColor=("yellow")
          }
      });
      e7.mousePressed(()=>{
          
          if(a7.visible===false&&s7.visible===false){
              a7.visible=true;
              gamemode=7;
              q7.shapeColor=("yellow")
          }
      });
      e8.mousePressed(()=>{
          
          if(a8.visible===false&&s8.visible===false){
              a8.visible=true;
              gamemode=7;
              q8.shapeColor=("yellow")
          }
      });
      e9.mousePressed(()=>{
          
          if(a9.visible===false&&s9.visible===false){
              a9.visible=true;
              gamemode=7;
              q9.shapeColor=("yellow")
          }
      });
  }
  
  if(gamemode===7){
      e1.mousePressed(()=>{
      
          if(a1.visible===false&&s1.visible===false){
              s1.visible=true;
              gamemode=8;
              q1.shapeColor=("pink")
          }
      });
      e2.mousePressed(()=>{
          
          if(a2.visible===false&&s2.visible===false){
              s2.visible=true;
              gamemode=8;
              q2.shapeColor=("pink")
          }
      });
      e3.mousePressed(()=>{
          
          if(a3.visible===false&&s3.visible===false){
              s3.visible=true;
              gamemode=8;
              q3.shapeColor=("pink")
          }
      });
      e4.mousePressed(()=>{
          
          if(a4.visible===false&&s4.visible===false){
              s4.visible=true;
              gamemode=8;
              q4.shapeColor=("pink")
          }
      });
      e5.mousePressed(()=>{
          
          if(a5.visible===false&&s5.visible===false){
              s5.visible=true;
              gamemode=8;
              q5.shapeColor=("pink")
          }
      });
      e6.mousePressed(()=>{
          
          if(a6.visible===false&&s6.visible===false){
              s6.visible=true;
              gamemode=8;
              q6.shapeColor=("pink")
          }
      });
      e7.mousePressed(()=>{
          
          if(a7.visible===false&&s7.visible===false){
              s7.visible=true;
              gamemode=8;
              q7.shapeColor=("pink")
          }
      });
      e8.mousePressed(()=>{
          
          if(a8.visible===false&&s8.visible===false){
              s8.visible=true;
              gamemode=8;
              q8.shapeColor=("pink")
          }
      });
      e9.mousePressed(()=>{
          
          if(a9.visible===false&&s9.visible===false){
              s9.visible=true;
              gamemode=8;
              q9.shapeColor=("pink")
          }
      });
  }
  
  if(gamemode===8){
      e1.mousePressed(()=>{
      
          if(a1.visible===false&&s1.visible===false){
              a1.visible=true;
              gamemode=9;
              q1.shapeColor=("yellow")
          }
      });
      e2.mousePressed(()=>{
          
          if(a2.visible===false&&s2.visible===false){
              a2.visible=true;
              gamemode=9;
              q2.shapeColor=("yellow")
          }
      });
      e3.mousePressed(()=>{
          
          if(a3.visible===false&&s3.visible===false){
              a3.visible=true;
              gamemode=9;
              q3.shapeColor=("yellow")
          }
      });
      e4.mousePressed(()=>{
          
          if(a4.visible===false&&s4.visible===false){
              a4.visible=true;
              gamemode=9;
              q4.shapeColor=("yellow")
          }
      });
      e5.mousePressed(()=>{
          
          if(a5.visible===false&&s5.visible===false){
              a5.visible=true;
              gamemode=9;
              q5.shapeColor=("yellow")
          }
      });
      e6.mousePressed(()=>{
          
          if(a6.visible===false&&s6.visible===false){
              a6.visible=true;
              gamemode=9;
              q6.shapeColor=("yellow")
          }
      });
      e7.mousePressed(()=>{
          
          if(a7.visible===false&&s7.visible===false){
              a7.visible=true;
              gamemode=9;
              q7.shapeColor=("yellow")
          }
      });
      e8.mousePressed(()=>{
          
          if(a8.visible===false&&s8.visible===false){
              a8.visible=true;
              gamemode=9;
              q8.shapeColor=("yellow")
          }
      });
      e9.mousePressed(()=>{
          
          if(a9.visible===false&&s9.visible===false){
              a9.visible=true;
              gamemode=9;
              q9.shapeColor=("yellow")
          }
      });
  }
  
  
}
